### ISSUE TITLE
"File Not Found" when trying to download explanations

### ISSUE THREAD

**Issue by y12uc231** [DFKI-NLP/emp-exp#2]
I was trying to download explanations with link in the repo, but it returned a bunch of "File Not Found" errors on those links. Is there a different way to down load those explanations.

**Comment by y12uc231** [comment]
<img width="700" alt="Screen Shot 2022-05-15 at 4 45 34 PM" src="https://user-images.githubusercontent.com/5621640/168499514-c943c0c0-6e5d-4148-abd9-30718a0813e8.png">

**Comment by rbtsbg** [comment]
Hi Satyapriya, 

thanks for making us aware of this issue. I just checked: The old links still work. For now, you may download the explanations following the links in the README here: 

https://github.com/DFKI-NLP/emp-exp/tree/2b8752f1363231545d55f5026ed811820e3ae6b9

On DFKI cloud, I recently copied all files from my personal space to a group folder because I was about to leave DFKI. This way I thought I could preserve the files and download links. Apparently, the new download links expired after I left. We will fix this issue soon. 

I apologize for any inconvenience. 

Regards,
Robert

**Comment by rbtsbg** [comment]
The download links in the README(s) are valid and active again. 

However, the links will probably expire in 2 months, which is why a more premanent solution should be implemented soon.

I will keep this issue open until this is done. 

Thanks again!

**Comment by rbtsbg** [comment]
All data moved to permanent storage location.
